// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmohqtrfeytchxvdqlby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tb2hxdHJmZXl0Y2h4dmRxbGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDE4NzYsImV4cCI6MjA3MzY3Nzg3Nn0.73yzlsBqMpJvQtnXYyVuD8W7MGs-8Lu70ACk9hIB8a8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});